"""add icd10/loinc/rxnorm lookup tables

Revision ID: 248f8fd7ea07
Revises: 6753bae4d5f5
Create Date: 2026-09-26 13:10:43.503136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248f8fd7ea07'
down_revision: Union[str, Sequence[str], None] = '6753bae4d5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icd10_codes',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_icd10_codes'))
    )
    op.create_table('loinc_codes',
    sa.Column('LOINC_NUM', sa.String(length=16), nullable=False),
    sa.Column('COMPONENT', sa.String(length=256), nullable=True),
    sa.Column('SYSTEM', sa.String(length=128), nullable=True),
    sa.Column('CLASS', sa.String(length=64), nullable=True),
    sa.Column('LONG_COMMON_NAME', sa.String(length=512), nullable=True),
    sa.Column('SHORTNAME', sa.String(length=128), nullable=True),
    sa.Column('STATUS', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('LOINC_NUM', name=op.f('pk_loinc_codes'))
    )
    op.create_table('rxnorm_codes',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('term_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_rxnorm_codes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rxnorm_codes')
    op.drop_table('loinc_codes')
    op.drop_table('icd10_codes')
    # ### end Alembic commands ###
