"""drop incorrect FK on claims_transactions.PATIENTINSURANCEID

Revision ID: 6753bae4d5f5
Revises: 0001
Create Date: 2026-09-26 10:28:14.667962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6753bae4d5f5'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_claims_transactions_PATIENTINSURANCEID'), 'claims_transactions', ['PATIENTINSURANCEID'], unique=False)
    op.drop_constraint(op.f('fk_claims_transactions_PATIENTINSURANCEID_payers'), 'claims_transactions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_claims_transactions_PATIENTINSURANCEID_payers'), 'claims_transactions', 'payers', ['PATIENTINSURANCEID'], ['Id'])
    op.drop_index(op.f('ix_claims_transactions_PATIENTINSURANCEID'), table_name='claims_transactions')
    # ### end Alembic commands ###
