"""add literature_abstracts table (pgvector)

Revision ID: 984cb67142e9
Revises: dee776fb3a30
Create Date: 2026-09-27 09:21:41.084840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '984cb67142e9'
down_revision: Union[str, Sequence[str], None] = 'dee776fb3a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('literature_abstracts',
    sa.Column('pmid', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pmid', name=op.f('pk_literature_abstracts'))
    )
    op.create_index(op.f('ix_literature_abstracts_topic'), 'literature_abstracts', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_literature_abstracts_topic'), table_name='literature_abstracts')
    op.drop_table('literature_abstracts')
    # ### end Alembic commands ###
