"""add Phase 2 domain model: investigations, tasks, artifacts, reports

Revision ID: dee776fb3a30
Revises: eb6cd5dd4485
Create Date: 2026-09-26 16:46:50.461165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee776fb3a30'
down_revision: Union[str, Sequence[str], None] = 'eb6cd5dd4485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.Id'], name=op.f('fk_investigations_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_patient_id'), 'investigations', ['patient_id'], unique=False)
    op.create_table('reports',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('evidence_complete', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_reports_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('investigation_id', name=op.f('pk_reports'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('tool', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_tasks_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_investigation_id'), 'tasks', ['investigation_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_artifacts_investigation_id_investigations')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_artifacts_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_investigation_id'), 'artifacts', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_artifacts_task_id'), 'artifacts', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_task_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_investigation_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_tasks_investigation_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('reports')
    op.drop_index(op.f('ix_investigations_patient_id'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
