"""drop unused icd10_codes table (SNOMED-CT, not ICD-10-CM, in this dataset)

Revision ID: eb6cd5dd4485
Revises: 248f8fd7ea07
Create Date: 2026-09-26 13:23:12.328528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6cd5dd4485'
down_revision: Union[str, Sequence[str], None] = '248f8fd7ea07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icd10_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icd10_codes',
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_icd10_codes'))
    )
    # ### end Alembic commands ###
